### ISSUE TITLE
Roll in a “target” option on <_a_> element?

### ISSUE THREAD

**Issue by tdom-du** [Mamaduka/bookmark-card#1]
Hi!
Love this plugin.
It fills a huge gap and need I’ve encountered putting up a couple new sites across our domain.

Any chance of rolling in a “target” attribute option on the <_a_> element?
i keep getting asked for that “target=blank” behavior.

I see how to do it with jquery appends. 
Having it native would be so much nicer!!

Thanks for considering it!!

**Comment by Mamaduka** [comment]
Hi @tdom-du,

I wanted to ship that feature in version 1. Unfortunately, there is/was a bug with Block Editor. When the `target` attribute is applied, it thinks the block is an image block.

Here's the original commit on a different branch - https://github.com/Mamaduka/bookmark-card/commit/5c5e89acbdf87176dd6ade8d18e7660108b04e57.

I will give it another shot to resolve the issue in near future.

**Comment by tdom-du** [comment]
Thanks for the info.

Ah, an upstream bug. Too bad that is the case! Kind of an odd one, at that.

I’ll keep an eye out and look around to see if any solutions on that block editor have come up.

Seems like you would not be the only bit by that.

T

**Comment by johnfleming** [comment]
Be great to have this added

**Comment by Mamaduka** [comment]
The feature is now available in version 2.2. Commit f40fa16aeca1bf0789b4129f6f657d5df91b1afb.
